##
## Aporeto
##
[[constraint]]
  name = "go.aporeto.io/trireme-lib"
  version = "^9.0.0"

[[override]]
  name = "github.com/aporeto-inc/netlink-go"
  version = "~1.4.0"

# the release version (v0.1.0)is too old, so we need to
# go to master right now
[[override]]
  name = "github.com/bvandewalle/go-ipset"
  branch = "master"

[[constraint]]
  name = "github.com/aporeto-inc/tg"
  version = "^2.22.0"


##
## Kubernetes
##
[[constraint]]
  name = "k8s.io/client-go"
  version = "^7.0.0"

# we are currently not directly dependent on it,
# however, we need to ensure we are on the right branch for
# all dependencies
[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "master"

[[constraint]]
  name = "k8s.io/gengo"
  branch = "master"

[[constraint]]
  name = "k8s.io/kube-openapi"
  branch = "master"


##
## 3rd Party
##
[[constraint]]
  name = "github.com/spf13/pflag"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "^1.0.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "^1.5.0"


##
## Prunes
##
[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    # this is the default anyway
    #non-go = false

  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false

  [[prune.project]]
    name = "k8s.io/kube-openapi"
    unused-packages = false
