apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager
rules:
- apiGroups: ["certmanager.k8s.io"]
  resources: ["certificates", "issuers"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets", "events", "endpoints", "services"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["list", "watch", "create", "delete", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager
subjects:
- namespace: default
  kind: ServiceAccount
  name: default
